// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurfLib.Data.Models;

#nullable disable

namespace SurfLib.Migrations
{
    [DbContext(typeof(SurfDbContext))]
    [Migration("20251102125329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurfLib.Data.Models.Maree", b =>
                {
                    b.Property<int>("MareeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maree_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MareeId"));

                    b.Property<int>("MareeCoefficient")
                        .HasColumnType("int")
                        .HasColumnName("maree_coefficient");

                    b.Property<bool>("MareeMoment")
                        .HasColumnType("bit")
                        .HasColumnName("maree_moment");

                    b.HasKey("MareeId")
                        .HasName("PK__maree__78B12A65FE2A31BD");

                    b.ToTable("maree");
                });

            modelBuilder.Entity("SurfLib.Data.Models.Prevision", b =>
                {
                    b.Property<int>("SpotId")
                        .HasColumnType("int")
                        .HasColumnName("spot_id");

                    b.Property<int>("MareeId")
                        .HasColumnType("int")
                        .HasColumnName("maree_id");

                    b.Property<TimeOnly>("PrevisionHeure")
                        .HasColumnType("time")
                        .HasColumnName("prevision_heure");

                    b.Property<DateOnly>("PrevisionDate")
                        .HasColumnType("date")
                        .HasColumnName("prevision_date");

                    b.HasKey("SpotId", "MareeId", "PrevisionHeure", "PrevisionDate")
                        .HasName("PK__previsio__77856B2E4A745E31");

                    b.HasIndex("MareeId");

                    b.ToTable("previsions");
                });

            modelBuilder.Entity("SurfLib.Data.Models.Spot", b =>
                {
                    b.Property<int>("SpotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("spot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpotId"));

                    b.Property<decimal>("SpotLat")
                        .HasColumnType("decimal(15, 6)")
                        .HasColumnName("spot_lat");

                    b.Property<decimal>("SpotLon")
                        .HasColumnType("decimal(15, 6)")
                        .HasColumnName("spot_lon");

                    b.Property<string>("SpotName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("spot_name");

                    b.HasKey("SpotId")
                        .HasName("PK__spot__330AF0F66245A61D");

                    b.HasIndex(new[] { "SpotName" }, "UQ__spot__8BF62491B7D336C7")
                        .IsUnique();

                    b.ToTable("spot");
                });

            modelBuilder.Entity("SurfLib.Data.Models.Prevision", b =>
                {
                    b.HasOne("SurfLib.Data.Models.Maree", "Maree")
                        .WithMany("Previsions")
                        .HasForeignKey("MareeId")
                        .IsRequired()
                        .HasConstraintName("FK__prevision__maree__3D5E1FD2");

                    b.HasOne("SurfLib.Data.Models.Spot", "Spot")
                        .WithMany("Previsions")
                        .HasForeignKey("SpotId")
                        .IsRequired()
                        .HasConstraintName("FK__prevision__spot___3C69FB99");

                    b.Navigation("Maree");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("SurfLib.Data.Models.Maree", b =>
                {
                    b.Navigation("Previsions");
                });

            modelBuilder.Entity("SurfLib.Data.Models.Spot", b =>
                {
                    b.Navigation("Previsions");
                });
#pragma warning restore 612, 618
        }
    }
}
