// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurfLib.Data.Models;

#nullable disable

namespace SurfLib.Migrations
{
    [DbContext(typeof(SurfDbContext))]
    [Migration("20251105090032_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SurfLib.Data.Models.Maree", b =>
                {
                    b.Property<int>("MareeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("maree_id");

                    b.Property<int>("MareeCoefficient")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maree_coefficient");

                    b.Property<DateOnly>("MareeDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("maree_date");

                    b.Property<double>("MareeHauteur")
                        .HasColumnType("REAL")
                        .HasColumnName("maree_hauteur");

                    b.Property<TimeOnly>("MareeHeure")
                        .HasColumnType("TEXT")
                        .HasColumnName("maree_heure");

                    b.Property<bool>("MareeMoment")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maree_moment");

                    b.Property<int>("SpotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MareeId")
                        .HasName("PK__maree__78B12A65FE2A31BD");

                    b.HasIndex("SpotId");

                    b.ToTable("maree");
                });

            modelBuilder.Entity("SurfLib.Data.Models.Spot", b =>
                {
                    b.Property<int>("SpotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("spot_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("SpotLat")
                        .HasColumnType("decimal(15, 7)")
                        .HasColumnName("spot_lat");

                    b.Property<decimal>("SpotLon")
                        .HasColumnType("decimal(15, 7)")
                        .HasColumnName("spot_lon");

                    b.Property<string>("SpotName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("spot_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("SpotId")
                        .HasName("PK__spot__330AF0F66245A61D");

                    b.HasIndex(new[] { "SpotName", "SpotLat", "SpotLon" }, "UQ_spot_name_lat_lon")
                        .IsUnique();

                    b.ToTable("spot");
                });

            modelBuilder.Entity("SurfLib.Data.Models.Maree", b =>
                {
                    b.HasOne("SurfLib.Data.Models.Spot", "Spot")
                        .WithMany("Marees")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("SurfLib.Data.Models.Spot", b =>
                {
                    b.Navigation("Marees");
                });
#pragma warning restore 612, 618
        }
    }
}
